# Generated by Django 5.1.15 on 2026-09-20 10:13

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('detection', '0001_initial'),
        ('geo', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Report',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('client_uuid', models.UUIDField(default=uuid.uuid4, help_text='Supplied by the mobile client so offline retries stay idempotent', unique=True)),
                ('image', models.ImageField(upload_to='reports/%Y/%m/')),
                ('thumbnail', models.ImageField(blank=True, upload_to='thumbs/%Y/%m/')),
                ('latitude', models.FloatField()),
                ('longitude', models.FloatField()),
                ('accuracy_m', models.FloatField(blank=True, null=True)),
                ('address', models.TextField(blank=True)),
                ('detection_status', models.CharField(choices=[('intact', 'No pothole found'), ('pothole_detected', 'Pothole detected'), ('needs_review', 'Needs review'), ('unknown', 'Analysis failed')], default='unknown', max_length=20)),
                ('confidence', models.FloatField(default=0.0)),
                ('severity', models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High')], default='low', max_length=10)),
                ('severity_score', models.FloatField(default=0.0)),
                ('severity_overridden', models.BooleanField(default=False)),
                ('detections', models.JSONField(blank=True, default=list)),
                ('workflow_status', models.CharField(choices=[('submitted', 'Submitted'), ('verified', 'Verified'), ('assigned', 'Assigned'), ('in_progress', 'In progress'), ('fixed', 'Fixed'), ('rejected', 'Rejected'), ('duplicate', 'Duplicate')], default='submitted', max_length=20)),
                ('report_count', models.PositiveIntegerField(default=1)),
                ('source', models.CharField(choices=[('web', 'Web'), ('android', 'Android'), ('live', 'Live video')], default='web', max_length=10)),
                ('notes', models.TextField(blank=True)),
                ('captured_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('duplicate_of', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='duplicates', to='reports.report')),
                ('model_version', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='detection.modelversion')),
                ('reporter', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reports', to=settings.AUTH_USER_MODEL)),
                ('ward', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reports', to='geo.ward')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='RepairProof',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('after_image', models.ImageField(upload_to='repairs/%Y/%m/')),
                ('note', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('report', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='repair_proofs', to='reports.report')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('body', models.TextField()),
                ('is_internal', models.BooleanField(default=False, help_text='Internal notes are hidden from the reporter')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('author', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('report', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='reports.report')),
            ],
            options={
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='Assignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('due_date', models.DateField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('assigned_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('officer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assigned_reports', to=settings.AUTH_USER_MODEL)),
                ('report', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assignments', to='reports.report')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='StatusHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('from_status', models.CharField(blank=True, max_length=20)),
                ('to_status', models.CharField(max_length=20)),
                ('note', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('changed_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('report', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='history', to='reports.report')),
            ],
            options={
                'verbose_name_plural': 'status history',
                'ordering': ['created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='report',
            index=models.Index(fields=['latitude', 'longitude'], name='report_latlng_idx'),
        ),
        migrations.AddIndex(
            model_name='report',
            index=models.Index(fields=['workflow_status', 'detection_status'], name='reports_rep_workflo_11265e_idx'),
        ),
        migrations.AddIndex(
            model_name='report',
            index=models.Index(fields=['-created_at'], name='reports_rep_created_f226dd_idx'),
        ),
        migrations.AddIndex(
            model_name='report',
            index=models.Index(fields=['severity'], name='reports_rep_severit_dc13aa_idx'),
        ),
        migrations.AddIndex(
            model_name='report',
            index=models.Index(fields=['ward'], name='reports_rep_ward_id_eb3dae_idx'),
        ),
    ]
