# Generated by Django 5.1.15 on 2026-09-20 10:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ModelVersion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120, unique=True)),
                ('file_path', models.CharField(help_text='Path to .pt weights, absolute or relative to the weights/ directory', max_length=500)),
                ('notes', models.TextField(blank=True)),
                ('conf_threshold', models.FloatField(default=0.6)),
                ('review_threshold', models.FloatField(default=0.3)),
                ('imgsz', models.PositiveIntegerField(default=640)),
                ('is_active', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-is_active', '-created_at'],
            },
        ),
    ]
