# Generated by Django 5.1.15 on 2026-09-20 10:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Ward',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('code', models.CharField(max_length=32, unique=True)),
                ('boundary', models.JSONField(blank=True, default=dict, help_text='GeoJSON Polygon or MultiPolygon geometry')),
                ('centroid_lat', models.FloatField(blank=True, null=True)),
                ('centroid_lng', models.FloatField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
    ]
